site_name: bs-python-utils
repo_url: https://github.com/bsalanie/bs-python-utils
site_url: https://bsalanie.github.io/bs-python-utils
site_description: my Python utilities
site_author: Bernard Salanie
edit_uri: edit/main/docs/
repo_name: bsalanie/bs-python-utils
copyright: Maintained by <a href="https://bsalanie.com">Bernard Salanie</a>.

nav:
  - Home: index.md
  - API Reference: 
    - General utilities:
      - error reporting and other utilities: bsutils.md
      - logging: bs_logging.md
      - math strings: bs_mathstr.md
      - timing routines: Timer.md
      - memory usage: bs_mem.md
    - Scientific:
      - Numpy: bsnputils.md
      - Scipy: bssputils.md
      - numerical interpolation and integration: chebyshev.md
      - Pandas: pandas_utils.md
      - statistics: bsstats.md
      - Sklearn: sklearn_utils.md
      - nonlinear dependence: distance_covariances.md
      - optimization: bs_opt.md
      - sparse integration for functions of Gaussians: bs_sparse_gaussian.md
      - bivariate quantiles and ranks: bivariate_quantiles.md
    - Plotting:
      - general interface: bs_plots.md
      - Matplotlib: bsmplutils.md
      - Seaborn: bs_seaborn.md
      - Altair: bs_altair.md
plugins:
  - search:
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')


# theme:
#   palette:
#     scheme: preference



theme:
  name: material
  features:
    - navigation.instant
    - search.highlight
    - navigation.expand
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bsalanie/bs-python-utils
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/bs-python-utils

markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - toc:
      permalink: true
  - admonition # add notes, warnings...
  - codehilite
  - toc
  - pymdownx.arithmatex: # for LaTeX
      generic: true  
extra_javascript: # for arithmatex
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
